version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: typescript
    versions:
    - "< 2.10, >= 2.9.a"
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
